

export const GOLF_API_FETCHED = "GOLF_API_FETCHED" 
export const GOLF_SCHEDULE_FETCHED = "GOLF_SCHEDULE_FETCHED"
export const WEATHER_FETCHED = "WEATHER_FETCHED"
export const IS_AUTHENITCATED = "IS_AUTHENTICATED"
export const SELECTED_TOUR = "SELECTED_TOUR"